Repository TidyBee/tidybee-agent, pull requests merged in 2024-03, with the labels that each got.

#133 insert a grade field inside the tidyscore table
  config/rules/basic.yml
  src/file_info.rs
  src/lib.rs
  src/my_files.rs
  src/tidy_algo.rs
  tests/assets/rules_folder/basic.yml
Labels: pre-beta

#136 Use cargo chef and multistaged docker build to speed up buildiong process
  .gitignore
  Dockerfile
Labels: enhancement, pre-beta

#139 Add a route in the server that will allow the HUB to retrieve the current configuration of the agent
  src/configuration.rs
  src/http/routes.rs
  src/lib.rs
  src/server.rs
  src/tidy_algo.rs
Labels: enhancement, pre-beta

#140 Build and push an container image to the repository container registry
  .github/workflows/docker.yaml
  Dockerfile
Labels: enhancement, pre-beta

#144 config: use absolute path at runtime
  src/configuration.rs
Labels: enhancement, pre-beta

#142 Implement error enum at crate level
  Cargo.lock
  Cargo.toml
  config/default.json
  src/configuration.rs
  src/error.rs
  src/file_lister.rs
  src/http/routes.rs
  src/lib.rs
  src/my_files.rs
  src/server.rs
  src/tidy_rules/perished.rs
Labels: enhancement, pre-beta, tests
